name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: pdm install

      - name: Black
        id: black
        run: |
          pdm run black GUNTAM/
          if ! git diff --quiet; then
            git diff > black.patch
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Fail on formating
        if: steps.black.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: black-formatting-patch
          path: black.patch
      
      - name: Flake8
        run: pdm run flake8        
      
      - name: Fail on black reformating
        if: steps.black.outputs.changed == 'true'
        run: exit 1
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: pdm install

      - name: Run tests
        run: pdm run pytest --cov=GUNTAM --ignore=tests/test_integration

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml

  Typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: pdm install

      - name: Run mypy
        run: pdm run mypy -p GUNTAM

  integration-test:
    runs-on: ubuntu-latest
    needs: [lint, test, Typing]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: pdm install

      - name: Run integration tests
        run: pdm run pytest tests/test_integration/test_integration_seed.py

  